# This needs to be fed into the build, otherwise something in Konflux
# sets $VERSION to the go version and it looks like we're shipping KEDA 1.23
# See: https://issues.redhat.com/browse/OCPBUGS-58129
# Chore: this will get used in the release policy, so update this when our version we're releasing changes
ARG CMA_VERSION=2.19.0
# This needs to be updated on rebases, we should be able to get this out of the changelog
# TODO(jkyros): add some test that verifies this matches the changelog
ARG HTTP_ADD_ON_VERSION=0.14.0
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25 as builder
ARG CMA_VERSION

LABEL stage=build
ENV GO_COMPLIANCE_INFO=0
ENV GO_COMPLIANCE_DEBUG=0
ENV GOTOOLCHAIN=local

ARG TARGETOS
ARG TARGETARCH
ENV ARCH=${TARGETARCH}

COPY /kedacore-http-add-on/ /src/
WORKDIR /src/

RUN LOCALBIN=/src/bin GOFLAGS='-tags=strictfipsruntime' make CGO=1 VERSION=${CMA_VERSION} build-operator

# MintMaker is not smart enough to figure out which "latest" you shipped,
# so we need to keep the hash here and let MintMaker security update it. No, I don't like it either.
# See: https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#enable-container-image-tag-versioning
# FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:850143255ee0d1915f09aaa09f6ed31f24086ba605c323badfbefa95b8c52b0e
ARG CMA_VERSION
ARG HTTP_ADD_ON_VERSION

WORKDIR /
RUN microdnf install -y tzdata && microdnf reinstall -y tzdata
RUN test -f /usr/share/zoneinfo/America/New_York

COPY --from=builder /src/bin/operator /usr/bin/http-add-on-operator

RUN mkdir /licenses
COPY --from=builder /src/LICENSE /licenses/

USER nobody

LABEL io.k8s.display-name="OpenShift KEDA HTTP Add-on Operator" \
      io.k8s.description="This is a component of OpenShift which provides HTTP-based autoscaling via the KEDA HTTP Add-on operator." \
      com.redhat.component="custom-metrics-autoscaler-http-add-on-operator-container" \
      name="custom-metrics-autoscaler/custom-metrics-autoscaler-http-add-on-operator-rhel9" \
      cpe="cpe:/a:redhat:openshift_custom_metrics_autoscaler:2.19::el9" \
      io.openshift.expose-services="" \
      io.openshift.tags="openshift,keda,http-add-on" \
      description="custom-metrics-autoscaler-http-add-on-operator-container" \
      maintainer="AOS node team <aos-node@redhat.com>"

# Chore: update this when openshift release changes
LABEL com.redhat.openshift.versions="v4.22"

LABEL version="${CMA_VERSION}"
LABEL http_add_on_version="${HTTP_ADD_ON_VERSION}"
LABEL release="2"

ENTRYPOINT ["/usr/bin/http-add-on-operator"]
