# This needs to be fed into the build, otherwise something in Konflux
# sets $VERSION to the go version and it looks like we're shipping KEDA 1.23
# See: https://issues.redhat.com/browse/OCPBUGS-58129
# Chore: this will get used in the release policy, so update this when our version we're releasing changes
ARG CMA_VERSION=2.19.0

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.26 as builder
ARG CMA_VERSION

LABEL stage=build

# Silence go compliance shim output
ENV GO_COMPLIANCE_INFO=0
ENV GO_COMPLIANCE_DEBUG=0

# Set go toolchain to local, this prevents it from
# downloading the latest version
ENV GOTOOLCHAIN=local

# If you don't set this as args, you don't seem to get them
ARG TARGETOS
ARG TARGETARCH

# The CMA makefile wants "ARCH", and will default to amd64 if not specified, 
# so we give it ARCH so we don't accidentally build an amd64 binary in our arm64 container
ENV ARCH=${TARGETARCH}

# Get the sources in here
COPY /custom-metrics-autoscaler-operator/ /src/

WORKDIR /src/

RUN GOFLAGS='-tags=strictfipsruntime' make CGO=1 VERSION=${CMA_VERSION} build

# MintMaker is not smart enough to figure out which "latest" you shipped, 
# so we need to keep the hash here and let MintMaker security update it. No, I don't like it either.
# See: https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#enable-container-image-tag-versioning
# FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93
ARG CMA_VERSION
LABEL stage=operator

# CVE-2024-12797 - remove once base image has the fix
# RUN microdnf install -y openssl-libs-1:3.2.2-6.el9_5.1

# install required tools for must-gather collection script
RUN INSTALL_PKGS=" \
      rsync \
      tar \
      openshift-clients \
      gzip \
      " && \
    microdnf install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    microdnf clean all

# Map TARGETARCH to the architecture naming used in artifacts.lock.yaml
# TODO(jkyros): Hilariously there was a bug that allowed this to work with the EC, and 
# now that they've fixed it, generic artifacts require an exception, so we're back to RPMs for now :) 
# ARG TARGETARCH
# RUN case "${TARGETARCH}" in \
#      amd64) FETCH_ARCH=x86_64 ;; \
#      arm64) FETCH_ARCH=aarch64 ;; \
#      s390x) FETCH_ARCH=s390x ;; \
#      ppc64le) FETCH_ARCH=ppc64le ;; \
#      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
#    esac && \
#    echo "Extracting openshift-client for architecture: ${FETCH_ARCH}" && \
#    tar -xzf /cachi2/output/deps/generic/openshift-client-linux-${FETCH_ARCH}.tar.gz -C /usr/bin/ oc kubectl && \
#    chmod +x /usr/bin/oc /usr/bin/kubectl

WORKDIR /
COPY --from=builder /src/resources/*.yaml /resources/
COPY --from=builder /src/bin/manager /usr/bin/
RUN ln -s /usr/bin/manager /manager

# This is also part of the gather script requirements
COPY --from=builder /src/must-gather/collection-scripts/* /usr/bin/

# TODO(jkyros): This seems weird, why do we do this?
RUN mkdir -p /src/cma-operator/app && \
    ln -s /resources /src/cma-operator/app/resources

# Need the license to pass enterprise pre-flight
RUN mkdir /licenses
COPY --from=builder /src/LICENSE /licenses/

#TODO(jkyros): I've goofed somewhere, it's looking here instead and not finding it, but why
RUN ln -s /resources /src/resources
USER nobody

# Need to specify a user to pass enterprise pre-flight
USER nobody

LABEL io.k8s.display-name="OpenShift Custom Metrics Autoscaler Operator" \
      io.k8s.description="This is a component of OpenShift which manages Custom Metrics Autoscaler." \
      com.redhat.component="custom-metrics-autoscaler-operator-container" \
      name="custom-metrics-autoscaler/custom-metrics-autoscaler-rhel9-operator" \
      cpe="cpe:/a:redhat:openshift_custom_metrics_autoscaler:2.19::el9" \
      summary="custom-metrics-autoscaler-operator" \
      io.openshift.expose-services="" \
      io.openshift.tags="openshift,custom-metrics-autoscaler-operator" \
      description="custom-metrics-autoscaler-operator-container" \
      maintainer="AOS node team <aos-node@redhat.com>"

# TODO(jkyros): I don't know what to do about the upstream labels yet, I don't think Konflux gets it for you
# LABEL upstream-version="${CI_KEDACORE_KEDA_UPSTREAM_VERSION}" \
#      upstream-vcs-ref="${CI_KEDACORE_KEDA_UPSTREAM_COMMIT}" \
#      upstream-vcs-type="git" \

# Chore: update this when openshift release changes
LABEL com.redhat.openshift.versions="v4.22"

LABEL version="${CMA_VERSION}"
# I don't know that we can auto-increment this without an additional pipeline stage or something, but if we omit it,
# we fail the metadata requirements, so we have to put _something_ here
LABEL release="3"

CMD ["/usr/bin/manager"]

