FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 as builder

LABEL stage=build

# Silence go compliance shim output
ENV GO_COMPLIANCE_INFO=0
ENV GO_COMPLIANCE_DEBUG=0

# Set go toolchain to local, this prevents it from
# downloading the latest version
ENV GOTOOLCHAIN=local

# If you don't set this as args, you don't seem to get them
ARG TARGETOS
ARG TARGETARCH

# The CMA makefile wants "ARCH", and will default to amd64 if not specified, 
# so we give it ARCH so we don't accidentally build an amd64 binary in our arm64 container
ENV ARCH=${TARGETARCH}

# Get the sources in here
COPY /custom-metrics-autoscaler-operator/ /src/

WORKDIR /src/

RUN find controllers && find resources

RUN GOFLAGS='-tags=strictfipsruntime' make CGO=1 build

# MintMaker is not smart enough to figure out which "latest" you shipped, 
# so we need to keep the hash here and let MintMaker security update it. No, I don't like it either.
# See: https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#enable-container-image-tag-versioning
# FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:e12131db2e2b6572613589a94b7f615d4ac89d94f859dad05908aeb478fb090f
LABEL stage=operator

# CVE-2024-12797 - remove once base image has the fix
# RUN microdnf install -y openssl-libs-1:3.2.2-6.el9_5.1

# install required tools for must-gather collection script
RUN INSTALL_PKGS=" \
      rsync \
      tar \
      openshift-clients \
      " && \
    microdnf install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    microdnf clean all

WORKDIR /
COPY --from=builder /src/resources/*.yaml /resources/
COPY --from=builder /src/bin/manager /usr/bin/
RUN ln -s /usr/bin/manager /manager

# This is also part of the gather script requirements
COPY --from=builder /src/must-gather/collection-scripts/* /usr/bin/

# TODO(jkyros): This seems weird, why do we do this?
RUN mkdir -p /src/cma-operator/app && \
    ln -s /resources /src/cma-operator/app/resources

# Need the license to pass enterprise pre-flight
RUN mkdir /licenses
COPY --from=builder /src/LICENSE /licenses/

#TODO(jkyros): I've goofed somewhere, it's looking here instead and not finding it, but why
RUN ln -s /resources /src/resources
USER nobody

# Need to specify a user to pass enterprise pre-flight
USER nobody

LABEL io.k8s.display-name="OpenShift Custom Metrics Autoscaler Operator" \
      io.k8s.description="This is a component of OpenShift which manages Custom Metrics Autoscaler." \
      com.redhat.component="custom-metrics-autoscaler-operator-container" \
      name="custom-metrics-autoscaler-operator-rhel-9" \
      summary="custom-metrics-autoscaler-operator" \
      io.openshift.expose-services="" \
      io.openshift.tags="openshift,custom-metrics-autoscaler-operator" \
      description="custom-metrics-autoscaler-operator-container" \
      maintainer="AOS node team <aos-node@redhat.com>"

# TODO(jkyros): I don't know what to do about the upstream labels yet, I don't think Konflux gets it for you
# LABEL upstream-version="${CI_KEDACORE_KEDA_UPSTREAM_VERSION}" \
#      upstream-vcs-ref="${CI_KEDACORE_KEDA_UPSTREAM_COMMIT}" \
#      upstream-vcs-type="git" \

# Chore: update this when openshift release changes
LABEL com.redhat.openshift.versions="v4.18"

# Chore: this will get used in the release policy, so update this when our version we're releasing changes
LABEL version="2.15.1"
# I don't know that we can auto-increment this without an additional pipeline stage or something, but if we omit it,
# we fail the metadata requirements, so we have to put _something_ here
LABEL release="6"

CMD ["/usr/bin/manager"]

