# This needs to be fed into the build, otherwise something in Konflux
# sets $VERSION to the go version and it looks like we're shipping KEDA 1.23
# See: https://issues.redhat.com/browse/OCPBUGS-58129
# Chore: this will get used in the release policy, so update this when our version we're releasing changes
ARG CMA_VERSION=2.18.1
#TODO(jkyros): There is something wrong with repo cert trust between the published RPM repos and the builder
# It's a builder though, so I dunno if I really care 
#FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.25 as builder
# TODO(jkyros): we need to switch back to brew once we _finally_ get a builder, this is temporarly
# until openshift catches up 
FROM registry.access.redhat.com/ubi9/go-toolset:1.26-1779719578 as builder
ARG CMA_VERSION

#FROM registry.redhat.io/ubi9/go-toolset as builder

LABEL stage=build
# Silence go compliance shim output
ENV GO_COMPLIANCE_INFO=0
ENV GO_COMPLIANCE_DEBUG=0

# Set go toolchain to local, this prevents it from
# downloading the latest version
ENV GOTOOLCHAIN=local

# If you don't set this as args, you don't seem to get them
ARG TARGETOS
ARG TARGETARCH

# The KEDA makefiles need this to get the right platform
ENV ARCH=${TARGETARCH}

RUN dnf install -y protobuf-compiler

# Install unzip (needed to extract protoc) and extract protoc from artifacts
# Using v21.9 instead of RHEL's 3.14.0 to get built-in support for proto3 optional fields
# RUN dnf install -y unzip && \
#    case "${TARGETARCH}" in \
#      amd64) PROTOC_ARCH=x86_64 ;; \
#      arm64) PROTOC_ARCH=aarch_64 ;; \
#      s390x) PROTOC_ARCH=s390_64 ;; \
#      ppc64le) PROTOC_ARCH=ppcle_64 ;; \
#      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
#    esac && \
#    echo "Installing protoc v21.9 for architecture: ${PROTOC_ARCH}" && \
#    unzip -q /cachi2/output/deps/generic/protoc-21.9-linux-${PROTOC_ARCH}.zip -d /usr/local && \
#    chmod +x /usr/local/bin/protoc

# Get the sources in here
COPY /kedacore-keda/ /src/

# And the tools, but separately
COPY /tools/ /tools/

WORKDIR /src/

RUN cd /tools/controller-tools/ && GOFLAGS="" go build -o /src/bin/controller-gen ./cmd/controller-gen
RUN cd /tools/mock/ && GOFLAGS="" go build -o /src/bin/mockgen ./mockgen
RUN cd /tools/protobuf/ && cd src/google && for f in $(find protobuf/ -name '*.proto'); do mkdir -p /usr/include/google/"$(dirname "$f")"; cp "$f" /usr/include/google/"$f"; done

# TODO(jkyros): we need to build with the proto3 optional option until we can get to 3.15, we don't have it yet
RUN printf '#!/bin/sh\nexec /usr/bin/protoc --experimental_allow_proto3_optional "$@"\n' > /usr/local/bin/protoc && \
    chmod +x /usr/local/bin/protoc


# this breaks controller-gen if it's there because it thinks it's "inconsistent vendoring" because it's just a random go.mod file hanging out
RUN rm -rf /src/hack/tooldeps
RUN LOCALBIN=/src/bin GOFLAGS='-tags=strictfipsruntime' make CGO=1 VERSION=${CMA_VERSION} adapter


# MintMaker is not smart enough to figure out which "latest" you shipped, 
# so we need to keep the hash here and let MintMaker security update it. No, I don't like it either.
# See: https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#enable-container-image-tag-versioning
# FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:24650313873554b6ba16c1a1b6b9f9142604f6ab735113e1695faf2dd07fdede
ARG CMA_VERSION

# CVE-2024-12797 - remove once base image has the fix
# RUN microdnf install -y openssl-libs-1:3.2.2-6.el9_5.1

WORKDIR /
RUN microdnf install -y tzdata && microdnf reinstall -y tzdata

# Fail if there is still a problem with tzdata
RUN test -f /usr/share/zoneinfo/America/New_York
COPY --from=builder /src/bin/keda-adapter /usr/bin/
RUN ln -s /usr/bin/keda-adapter /keda-adapter

# Compliance
RUN mkdir /licenses
COPY --from=builder /src/LICENSE /licenses/

USER nobody

LABEL io.k8s.display-name="OpenShift Custom Metrics Autoscaler Adapter" \
      io.k8s.description="This is a component of OpenShift which provides a custom metrics API endpoint for pod autoscaling." \
      com.redhat.component="custom-metrics-autoscaler-adapter-container" \
      name="custom-metrics-autoscaler/custom-metrics-autoscaler-adapter-rhel9" \
      cpe="cpe:/a:redhat:openshift_custom_metrics_autoscaler:2.18::el9" \
      summary="custom-metrics-autoscaler-adapter" \
      io.openshift.expose-services="" \
      io.openshift.tags="openshift,custom-metrics-autoscaler-adapter" \
      description="custom-metrics-autoscaler-container-adapter" \
      maintainer="AOS node team <aos-node@redhat.com>"

# TODO(jkyros): I don't know what to do about the upstream labels yet, I don't think Konflux gets it for you
#LABEL upstream-version="${CI_KEDACORE_KEDA_UPSTREAM_VERSION}" \
#      upstream-vcs-ref="${CI_KEDACORE_KEDA_UPSTREAM_COMMIT}" \
#      upstream-vcs-type="git" \

# Chore: update this when openshift release changes
LABEL com.redhat.openshift.versions="v4.20"

LABEL version="${CMA_VERSION}"
# I don't know that we can auto-increment this without an additional pipeline stage or something, but if we omit it,
# we fail the metadata requirements, so we have to put _something_ here
LABEL release="2"


ENTRYPOINT ["/usr/bin/keda-adapter", "--secure-port=6443", "--logtostderr=true", "--v=0"]
