apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: single-arch-build-pipeline
spec:
  tasks:
  - name: init
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:08e18a4dc5f947c1d20e8353a19d013144bea87b72f67236b165dd4778523951
      - name: kind
        value: task
    params:
    - name: image-url
      value: "$(params.output-image)"
    - name: rebuild
      value: "$(params.rebuild)"
    - name: skip-checks
      value: "$(params.skip-checks)"
  - name: clone-repository
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:be82c55346e8810bd1edc5547f864064da6945979baccca7dfc99990b392a02b
      - name: kind
        value: task
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    runAfter:
    - init
    params:
    - name: url
      value: "$(params.git-url)"
    - name: revision
      value: "$(params.revision)"
    - name: ociStorage
      value: "$(params.output-image).git"
    - name: ociArtifactExpiresAfter
      value: "$(params.image-expires-after)"
    workspaces:
    - name: basic-auth
      workspace: git-auth
  - name: prefetch-dependencies
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: prefetch-dependencies-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:e38599be9aafc4622545e66673c5bc2292b323834c5d852f4a39cb7d01784574
      - name: kind
        value: task
    params:
    - name: input
      value: "$(params.prefetch-input)"
    - name: hermetic
      value: "$(params.hermetic)"
    - name: dev-package-managers
      value: $(params.prefetch-dev-package-managers-enabled)
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image).prefetch
    - name: ociArtifactExpiresAfter
      value: $(params.image-expires-after)
  - name: build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: buildah-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.4@sha256:d78d8abba7a84faa391d8b3b23be49ad8c09e9b1c0cabaed3919f64100cead2d
      - name: kind
        value: task
    runAfter:
    - clone-repository
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    params:
    - name: IMAGE
      value: "$(params.output-image)"
    - name: DOCKERFILE
      value: "$(params.dockerfile)"
    - name: CONTEXT
      value: "$(params.path-context)"
    - name: HERMETIC
      value: "$(params.hermetic)"
    - name: PREFETCH_INPUT
      value: "$(params.prefetch-input)"
    - name: IMAGE_EXPIRES_AFTER
      value: "$(params.image-expires-after)"
    - name: COMMIT_SHA
      value: "$(tasks.clone-repository.results.commit)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
  - name: build-source-image
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: source-build-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-source-build-oci-ta:0.3@sha256:bfec1fabb0ed7c191e6c85d75e6cc577a04cabe9e6b35f9476529e8e5b3c0c82
      - name: kind
        value: task
    when:
    - input: "$(tasks.init.results.build)"
      operator: in
      values:
      - 'true'
    - input: "$(params.build-source-image)"
      operator: in
      values:
      - 'true'
    runAfter:
    - build-container
    params:
    - name: BINARY_IMAGE
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: BINARY_IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
  - name: deprecated-base-image-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:1d07d16810c26713f3d875083924d93697900147364360587ccb5a63f2c31012
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container.results.IMAGE_DIGEST)
  - name: clair-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clair-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:893ffa3ce26b061e21bb4d8db9ef7ed4ddd4044fe7aa5451ef391034da3ff759
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: ecosystem-cert-preflight-checks
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: ecosystem-cert-preflight-checks
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:4bafcaab0f0c998a89a1cc33bdbbf74f39eea52e6c0e43013c356a322f94940f
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: sast-snyk-check
    params:
    - name: image-digest
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: sast-snyk-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:fe5e5ba3a72632cd505910de2eacd62c9d11ed570c325173188f8d568ac60771
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
  - name: sast-shell-check
    params:
    - name: image-digest
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - build-image-index
    taskRef:
      params:
      - name: name
        value: sast-shell-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:bf7bdde00b7212f730c1356672290af6f38d070da2c8a316987b5c32fd49e0b9
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sast-unicode-check
    params:
    - name: image-digest
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    runAfter:
    - build-image-index
    taskRef:
      params:
      - name: name
        value: sast-unicode-check-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.3@sha256:a2bde66f6b4164620298c7d709b8f08515409404000fa1dc2260d2508b135651
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: clamav-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clamav-scan
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:cce2dfcc5bd6e91ee54aacdadad523b013eeae5cdaa7f6a4624b8cbcc040f439
      - name: kind
        value: task
    when:
    - input: "$(params.skip-checks)"
      operator: in
      values:
      - 'false'
    runAfter:
    - build-container
    params:
    - name: image-digest
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: image-url
      value: "$(tasks.build-container.results.IMAGE_URL)"
  params:
  - name: git-url
    type: string
    description: Source Repository URL
  - name: revision
    type: string
    description: Revision of the Source Repository
    default: ''
  - name: output-image
    type: string
    description: Fully Qualified Output Image
  - name: path-context
    type: string
    description: Path to the source code of an application's component from where to build image.
    default: "."
  - name: dockerfile
    type: string
    description: Path to the Dockerfile inside the context specified by parameter path-context
    default: Dockerfile
  - name: rebuild
    type: string
    description: Force rebuild image
    default: 'false'
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ''
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: "false"
    description: Enable dev-package-managers in prefetch task
    name: prefetch-dev-package-managers-enabled
    type: string
  - name: java
    type: string
    description: Java build
    default: 'false'
  - name: image-expires-after
    description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
    default: ''
  - name: build-source-image
    type: string
    description: Build a source image.
    default: 'false'
  workspaces:
  - name: git-auth
    optional: true
  results:
  - name: IMAGE_URL
    description: ''
    value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: IMAGE_DIGEST
    description: ''
    value: "$(tasks.build-container.results.IMAGE_DIGEST)"
  - name: CHAINS-GIT_URL
    description: ''
    value: "$(tasks.clone-repository.results.url)"
  - name: CHAINS-GIT_COMMIT
    description: ''
    value: "$(tasks.clone-repository.results.commit)"
  finally:
  - name: show-sbom
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:beb0616db051952b4b861dd8c3e00fa1c0eccbd926feddf71194d3bb3ace9ce7
      - name: kind
        value: task
    params:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
  - name: show-summary
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:3f6e8513cbd70f0416eb6c6f2766973a754778526125ff33d8e3633def917091
      - name: kind
        value: task
    params:
    - name: pipelinerun-name
      value: "$(context.pipelineRun.name)"
    - name: git-url
      value: "$(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)"
    - name: image-url
      value: "$(params.output-image)"
    - name: build-task-status
      value: "$(tasks.build-container.status)"
